FROM node:lts-alpine as build-stage

RUN mkdir -p /home/tricky/frontend/app

RUN chown node /home/tricky/frontend/app

USER node

WORKDIR /home/tricky/frontend/app

COPY --chown=node:node package-lock.json package.json ./

RUN npm ci

COPY --chown=node:node . .

RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /home/tricky/frontend/app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]