FROM node:12-stretch

RUN mkdir -p /home/tick/backend

RUN chown trickyBack /home/tick/backend

USER trickyBack

WORKDIR /home/tick/backend

COPY --chown=trickyBack:trickyBack package-lock.json package.json ./

RUN npm ci

COPY --chown=trickyBack:trickyBack . .

CMD [ "node", "index.js"]