version: "3"

services:
  mongo_db:
    container_name: "tricky_db"
    image: "mongo:latest"
    restart: "always"
    ports:
      - "27017:27017"
  api:
    build: 
      context: ./backend/
    container_name: "tricky_backend"
    ports:
      - "5000:5000"
    env_file: ./backend/.env
    environment:
      API_PORT: 5000
      DB_MONGO_HOST: mongo_db
      DB_MONGO_PORT: $DB_MONGO_PORT
      DB_MONGO_NAME: $DB_MONGO_NAME
    links:
      - mongo_db
  front:
    build: ./frontend/
    container_name: "tricky_frontend"
    ports:
      - "80:80"
