FROM node:12-stretch

RUN mkdir -p /home/tricky/backend

RUN chown node /home/tricky/backend

USER node

WORKDIR /home/tricky/backend

COPY --chown=node:node package-lock.json package.json ./

RUN npm ci

COPY --chown=node:node . .

CMD [ "node", "index.js"]